#ifndef SPELL_DEF
#define SPELL_DEF(className, spellName)
#endif

SPELL_DEF(AcidSplash, ACID_SPLASH)
SPELL_DEF(FireBolt, FIRE_BOLT)
SPELL_DEF(RayOfFrost, RAY_OF_FROST)
SPELL_DEF(ShockingGrasp, SHOCKING_GRASP)
SPELL_DEF(BurningHands, BURNING_HANDS)
SPELL_DEF(MageArmor, MAGE_ARMOR)
SPELL_DEF(MagicMissile, MAGIC_MISSILE)
SPELL_DEF(Shield, SHIELD)
SPELL_DEF(Thunderwave, THUNDERWAVE)

#undef SPELL_DEF
