#ifndef KERF_ENUMS_COMMON_H
#define KERF_ENUMS_COMMON_H

enum ARCHETYPE {
	BRAWLER = 0,
	ROGUE,
	RANGER,
	DAMAGE_CASTER,
	SUPPORT_CASTER,
	N_ARCHETYPES
};


enum ACTION_TIMING_BIT {
	ACTION_TIMING_INVALID =			0,
	ACTION_TIMING_PASSIVE =			1 << 0,
	ACTION_TIMING_REACTION =			1 << 1,
	ACTION_TIMING_ACTION =			1 << 2,
	ACTION_TIMING_BONUS_ACTION =		1 << 3,
};
typedef uint16_t ACTION_TIMING;


enum ABILITY_SCORES {
	STR = 0,
	DEX,
	CON,
	INT,
	WIS,
	CHA,
	N_ABILITY_SCORES
};

#endif // !KERF_ENUMS_COMMON_H

